//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Мухутдинов.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abiturenti
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Abiturenti()
        {
            this.Lgotnie_documenti = new HashSet<Lgotnie_documenti>();
            this.Obrazovanie = new HashSet<Obrazovanie>();
            this.Pasportnie_dannie = new HashSet<Pasportnie_dannie>();
            this.Zaconie_predstaviteli = new HashSet<Zaconiepredstaviteli>();
            this.Zaivlenie = new HashSet<Zaivlenie>();
        }
    
        public long Kod_abiturenta { get; set; }
        public string FIO { get; set; }
        public System.DateTime Date_of_birth { get; set; }
        public Nullable<int> Telefon { get; set; }
        public string E_mail { get; set; }
        public string Adress_prowivanie { get; set; }
        public string language { get; set; }
        public Nullable<bool> Obchiwitie { get; set; }
        public Nullable<bool> Invalidnost { get; set; }
        public Nullable<bool> OVZ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lgotnie_documenti> Lgotnie_documenti { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Obrazovanie> Obrazovanie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pasportnie_dannie> Pasportnie_dannie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zaconiepredstaviteli> Zaconie_predstaviteli { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Zaivlenie> Zaivlenie { get; set; }
    }
}
