//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Мухутдинов.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lgotnie_documenti
    {
        public long id { get; set; }
        public long Seria { get; set; }
        public long Nomer { get; set; }
        public Nullable<System.DateTime> Date_vidachi { get; set; }
        public string Kem_vidan { get; set; }
        public long kod_abiturinta { get; set; }
    
        public virtual Abiturenti Abiturenti { get; set; }
    }
}
