//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Мухутдинов.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obrazovanie
    {
        public long id { get; set; }
        public string Nazvanie_doc { get; set; }
        public long Seria { get; set; }
        public long Nomer_doc { get; set; }
        public Nullable<float> Srednie_ball { get; set; }
        public Nullable<long> kod_abiturienta { get; set; }
    
        public virtual Abiturenti Abiturenti { get; set; }
    }
}
