//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Мухутдинов.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pasportnie_dannie
    {
        public long id { get; set; }
        public Nullable<long> Seria_pasporta { get; set; }
        public Nullable<System.DateTime> Date_vidachi { get; set; }
        public string Kem_vidan { get; set; }
        public string Grawdanstvo { get; set; }
        public string Nationality { get; set; }
        public long kod_abiturienta { get; set; }
    
        public virtual Abiturenti Abiturenti { get; set; }
    }
}
