//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Мухутдинов.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zaconiepredstaviteli
    {
        public long id { get; set; }
        public long Kod_abiturenta { get; set; }
        public string FIO { get; set; }
        public string Stepen_rodstva { get; set; }
        public int Telefon { get; set; }
        public string Mesto_rabotu { get; set; }
        public string Adress_prowivanie { get; set; }
    
        public virtual Abiturenti Abiturenti { get; set; }
    }
}
