//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Мухутдинов.NewFolder1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zaivlenie
    {
        public long id { get; set; }
        public Nullable<System.DateTime> Date_zaivlenie { get; set; }
        public long Kod_abiturenta { get; set; }
        public Nullable<long> Kod_spec { get; set; }
    
        public virtual Abiturenti Abiturenti { get; set; }
        public virtual Specilization Specilization { get; set; }
    }
}
